# Generated by Django 5.0.8 on 2024-08-22 14:11

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('sender', 'Sender'), ('private', 'Private'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], default='private')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_admins_join_games', models.BooleanField(default=True)),
                ('can_admins_create_games', models.BooleanField(default=True)),
                ('can_admins_press_other_buttons', models.BooleanField(default=False)),
                ('min_punish_time_for_rand_choice', models.DurationField(default=datetime.timedelta(seconds=60))),
                ('max_punish_time_for_rand_choice', models.DurationField(default=None, null=True)),
                ('can_admins_ignore_time_limitations', models.BooleanField(default=False)),
                ('can_members_create_public_punishments', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField(null=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('left', 'Left'), ('restricted', 'Restricted'), ('member', 'Member'), ('admin', 'Admin'), ('owner', 'Owner')], default='member')),
                ('is_anon', models.BooleanField(default=False)),
                ('interaction_level', models.TextField(choices=[('restricted', 'Restricted'), ('based_on_status', 'Based_on_status'), ('can_administrate', 'Can_administrate')], default='based_on_status')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(through='bot.ChatMember', to='bot.user'),
        ),
    ]
