# Generated by Django 5.0.8 on 2024-08-31 18:29

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessSettingsObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_join_games', models.BooleanField(default=True)),
                ('can_create_games', models.BooleanField(default=True)),
                ('can_press_other_buttons', models.BooleanField(default=False)),
                ('min_punish_time_for_rand_choice', models.DurationField(default=datetime.timedelta(seconds=60))),
                ('max_punish_time_for_rand_choice', models.DurationField(default=datetime.timedelta(days=365), null=True)),
                ('can_create_public_punishments', models.BooleanField(default=False)),
                ('can_delete_public_punishments', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('sender', 'Sender'), ('private', 'Private'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], default='private')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_ban_statistic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField(null=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.TextField(choices=[('chat', 'Chat'), ('admins', 'Admins'), ('group', 'Group'), ('member', 'Member')], default='chat')),
                ('target_id', models.TextField()),
                ('settings_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.accesssettingsobject')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chat')),
            ],
        ),
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default='untitled group')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chat')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('left', 'Left'), ('restricted', 'Restricted'), ('member', 'Member'), ('admin', 'Admin'), ('owner', 'Owner')], default='member')),
                ('is_anon', models.BooleanField(default=False)),
                ('interaction_level', models.TextField(choices=[('restricted', 'Restricted'), ('based_on_status', 'Based_on_status'), ('can_administrate', 'Can_administrate')], default='based_on_status')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chat')),
                ('settings_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.accessgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(through='bot.ChatMember', to='bot.user'),
        ),
    ]
