# Generated by Django 5.1 on 2024-08-16 15:45

import bot.models.Chat
import bot.models.User
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('sender', 'Sender'), ('private', 'Private'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], default='private')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_admins_join_games', models.BooleanField(default=True)),
                ('can_admins_create_games', models.BooleanField(default=True)),
                ('min_punish_time_for_rand_choice', models.DurationField(default=datetime.timedelta(seconds=60))),
                ('max_punish_time_for_rand_choice', models.DurationField(default=datetime.timedelta(days=1))),
                ('can_admins_ignore_time_limitations', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField(null=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('can_interact_with_bot', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=models.SET(bot.models.Chat.get_sentinel), to='bot.chat')),
                ('user', models.ForeignKey(on_delete=models.SET(bot.models.User.get_sentinel), to='bot.user')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(through='bot.ChatMember', to='bot.user'),
        ),
    ]
