# Generated by Django 5.1 on 2024-08-14 16:18

import bot.models.User
import datetime
import django.core.validators
import django.db.models.deletion
import games.models.Punishment
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default='untitled')),
                ('time', models.DurationField(default=datetime.timedelta(seconds=18000))),
                ('is_public', models.BooleanField(default=False)),
                ('access_level', models.TextField(choices=[('user', 'User'), ('admin', 'Admin'), ('super_admin', 'Super_admin')], default='user')),
                ('created_by', models.ForeignKey(on_delete=bot.models.User.get_sentinel, to='bot.user')),
            ],
        ),
        migrations.CreateModel(
            name='RandomChoiceGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_players_count', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)])),
                ('max_players_count', models.PositiveIntegerField(default=6)),
                ('losers_count', models.PositiveIntegerField(default=1)),
                ('is_creator_playing', models.BooleanField(default=True)),
                ('auto_start_game', models.TextField(choices=[('no', 'No'), ('at_max_players', 'At_max_players'), ('by_timer', 'By_timer'), ('at_max_players_and_by_timer', 'At_max_players_and_by_timer'), ('at_max_players_or_by_timer', 'At_max_players_or_by_timer')], default='at_max_players')),
                ('auto_start_timer', models.DurationField(default=None, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_timer', models.DurationField(default=None, null=True)),
                ('creator', models.ForeignKey(on_delete=bot.models.User.get_sentinel, related_name='created_random_choice_games', to='bot.user')),
                ('punishment', models.ForeignKey(on_delete=models.SET(games.models.Punishment.get_sentinel), to='games.punishment')),
            ],
        ),
        migrations.CreateModel(
            name='RandomChoiceGamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.randomchoicegame')),
                ('user', models.ForeignKey(on_delete=bot.models.User.get_sentinel, to='bot.user')),
            ],
        ),
        migrations.AddField(
            model_name='randomchoicegame',
            name='players',
            field=models.ManyToManyField(related_name='participated_random_choice_games', through='games.RandomChoiceGamePlayer', to='bot.user'),
        ),
    ]
