# Generated by Django 5.0.8 on 2024-10-25 16:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):
    sql = """
    UPDATE games_randomchoicegameresult AS r
    SET game_id = g.id
    FROM games_randomchoicegame AS g
    WHERE r.id = g.result_id
    """

    schema_editor.execute(sql)


def backward(apps, schema_editor):
    sql = """
    UPDATE games_randomchoicegame AS g
    SET result_id = r.id
    FROM games_randomchoicegameresult AS r
    WHERE g.id = r.game_id
    """

    schema_editor.execute(sql)


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomchoicegame',
            name='autostart_at',
        ),
        migrations.AddField(
            model_name='randomchoicegame',
            name='autostart_timer',
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='randomchoicegame',
            name='autostart_timer_started_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='randomchoicegameresult',
            name='game',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result',
                                       to='games.randomchoicegame'),
        ),
        migrations.RunPython(forward, backward),
        migrations.RemoveField(
            model_name='randomchoicegame',
            name='result',
        ),
        migrations.CreateModel(
            name='HiddenMinesGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_creator_playing', models.BooleanField(default=True)),
                ('is_opened_to_join', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hidden_mines_games',
                                              to='bot.chatmember')),
                ('punishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.punishment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HiddenMinesGameField',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='games.hiddenminesgame')),
            ],
        ),
        migrations.CreateModel(
            name='HiddenMinesGameCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('type', models.TextField(choices=[('mine', 'Mine'), ('empty', 'Empty')], default='empty')),
                ('is_opened', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='games.hiddenminesgamefield')),
            ],
        ),
        migrations.CreateModel(
            name='HiddenMinesGamePlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('join_at', models.DateTimeField(auto_now_add=True)),
                ('chat_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chatmember')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.hiddenminesgame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HiddenMinesGameLoser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.hiddenminesgameplayer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hiddenminesgame',
            name='players',
            field=models.ManyToManyField(related_name='participated_hidden_mines_games', through='games.HiddenMinesGamePlayer', to='bot.chatmember'),
        ),
        migrations.CreateModel(
            name='HiddenMinesGameResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result',
                                              to='games.hiddenminesgame')),
                ('losers', models.ManyToManyField(through='games.HiddenMinesGameLoser', to='games.hiddenminesgameplayer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hiddenminesgameloser',
            name='game_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.hiddenminesgameresult'),
        ),
    ]
