# Generated by Django 5.0.8 on 2024-10-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomchoicegame',
            name='autostart_at',
        ),
        migrations.AddField(
            model_name='randomchoicegame',
            name='autostart_timer',
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='randomchoicegame',
            name='autostart_timer_started_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
